export const locals = [
	[1,"af","Afrikaans"],
	[2,"af-ZA","Afrikaans (South Africa)"],
	[3,"ar","Arabic"],
	[4,"ar-AE","Arabic (U.A.E.)"],
	[5,"ar-BH","Arabic (Bahrain)"],
	[6,"ar-DZ","Arabic (Algeria)"],
	[7,"ar-EG","Arabic (Egypt)"],
	[8,"ar-IQ","Arabic (Iraq)"],
	[9,"ar-JO","Arabic (Jordan)"],
	[10,"ar-KW","Arabic (Kuwait)"],
	[11,"ar-LB","Arabic (Lebanon)"],
	[12,"ar-LY","Arabic (Libya)"],
	[13,"ar-MA","Arabic (Morocco)"],
	[14,"ar-OM","Arabic (Oman)"],
	[15,"ar-QA","Arabic (Qatar)"],
	[16,"ar-SA","Arabic (Saudi Arabia)"],
	[17,"ar-SY","Arabic (Syria)"],
	[18,"ar-TN","Arabic (Tunisia)"],
	[19,"ar-YE","Arabic (Yemen)"],
	[20,"az","Azeri (Latin)"],
	[21,"az-AZ","Azeri (Latin) (Azerbaijan)"],
	[22,"az-AZ-1","Azeri (Cyrillic) (Azerbaijan)"],
	[23,"be","Belarusian"],
	[24,"be-BY","Belarusian (Belarus)"],
	[25,"bg","Bulgarian"],
	[26,"bg-BG","Bulgarian (Bulgaria)"],
	[27,"bs-BA","Bosnian (Bosnia and Herzegovina)"],
	[28,"ca","Catalan"],
	[29,"ca-ES","Catalan (Spain)"],
	[30,"cs","Czech"],
	[31,"cs-CZ","Czech (Czech Republic)"],
	[32,"cy","Welsh"],
	[33,"cy-GB","Welsh (United Kingdom)"],
	[34,"da","Danish"],
	[35,"da-DK","Danish (Denmark)"],
	[36,"de","German"],
	[37,"de-AT","German (Austria)"],
	[38,"de-CH","German (Switzerland)"],
	[39,"de-DE","German (Germany)"],
	[40,"de-LI","German (Liechtenstein)"],
	[41,"de-LU","German (Luxembourg)"],
	[42,"dv","Divehi"],
	[43,"dv-MV","Divehi (Maldives)"],
	[44,"el","Greek"],
	[45,"el-GR","Greek (Greece)"],
	[46,"en","English"],
	[47,"en-AU","English (Australia)"],
	[48,"en-BZ","English (Belize)"],
	[49,"en-CA","English (Canada)"],
	[50,"en-CB","English (Caribbean)"],
	[51,"en-GB","English (United Kingdom)"],
	[52,"en-IE","English (Ireland)"],
	[53,"en-JM","English (Jamaica)"],
	[54,"en-NZ","English (New Zealand)"],
	[55,"en-PH","English (Republic of the Philippines)"],
	[56,"en-TT","English (Trinidad and Tobago)"],
	[57,"en-US","English (United States)"],
	[58,"en-ZA","English (South Africa)"],
	[59,"en-ZW","English (Zimbabwe)"],
	[60,"eo","Esperanto"],
	[61,"es","Spanish"],
	[62,"es-AR","Spanish (Argentina)"],
	[63,"es-BO","Spanish (Bolivia)"],
	[64,"es-CL","Spanish (Chile)"],
	[65,"es-CO","Spanish (Colombia)"],
	[66,"es-CR","Spanish (Costa Rica)"],
	[67,"es-DO","Spanish (Dominican Republic)"],
	[68,"es-EC","Spanish (Ecuador)"],
	[69,"es-ES","Spanish (Castilian)"],
	[70,"es-ES-1","Spanish (Spain)"],
	[71,"es-GT","Spanish (Guatemala)"],
	[72,"es-HN","Spanish (Honduras)"],
	[73,"es-MX","Spanish (Mexico)"],
	[74,"es-NI","Spanish (Nicaragua)"],
	[75,"es-PA","Spanish (Panama)"],
	[76,"es-PE","Spanish (Peru)"],
	[77,"es-PR","Spanish (Puerto Rico)"],
	[78,"es-PY","Spanish (Paraguay)"],
	[79,"es-SV","Spanish (El Salvador)"],
	[80,"es-UY","Spanish (Uruguay)"],
	[81,"es-VE","Spanish (Venezuela)"],
	[82,"et","Estonian"],
	[83,"et-EE","Estonian (Estonia)"],
	[84,"eu","Basque"],
	[85,"eu-ES","Basque (Spain)"],
	[86,"fa","Farsi"],
	[87,"fa-IR","Farsi (Iran)"],
	[88,"fi","Finnish"],
	[89,"fi-FI","Finnish (Finland)"],
	[90,"fo","Faroese"],
	[91,"fo-FO","Faroese (Faroe Islands)"],
	[92,"fr","French"],
	[93,"fr-BE","French (Belgium)"],
	[94,"fr-CA","French (Canada)"],
	[95,"fr-CH","French (Switzerland)"],
	[96,"fr-FR","French (France)"],
	[97,"fr-LU","French (Luxembourg)"],
	[98,"fr-MC","French (Principality of Monaco)"],
	[99,"gl","Galician"],
	[100,"gl-ES","Galician (Spain)"],
	[101,"gu","Gujarati"],
	[102,"gu-IN","Gujarati (India)"],
	[103,"he","Hebrew"],
	[104,"he-IL","Hebrew (Israel)"],
	[105,"hi","Hindi"],
	[106,"hi-IN","Hindi (India)"],
	[107,"hr","Croatian"],
	[108,"hr-BA","Croatian (Bosnia and Herzegovina)"],
	[109,"hr-HR","Croatian (Croatia)"],
	[110,"hu","Hungarian"],
	[111,"hu-HU","Hungarian (Hungary)"],
	[112,"hy","Armenian"],
	[113,"hy-AM","Armenian (Armenia)"],
	[114,"id","Indonesian"],
	[115,"id-ID","Indonesian (Indonesia)"],
	[116,"is","Icelandic"],
	[117,"is-IS","Icelandic (Iceland)"],
	[118,"it","Italian"],
	[119,"it-CH","Italian (Switzerland)"],
	[120,"it-IT","Italian (Italy)"],
	[121,"ja","Japanese"],
	[122,"ja-JP","Japanese (Japan)"],
	[123,"ka","Georgian"],
	[124,"ka-GE","Georgian (Georgia)"],
	[125,"kk","Kazakh"],
	[126,"kk-KZ","Kazakh (Kazakhstan)"],
	[127,"kn","Kannada"],
	[128,"kn-IN","Kannada (India)"],
	[129,"ko","Korean"],
	[130,"ko-KR","Korean (Korea)"],
	[131,"kok","Konkani"],
	[132,"kok-IN","Konkani (India)"],
	[133,"ky","Kyrgyz"],
	[134,"ky-KG","Kyrgyz (Kyrgyzstan)"],
	[135,"lt","Lithuanian"],
	[136,"lt-LT","Lithuanian (Lithuania)"],
	[137,"lv","Latvian"],
	[138,"lv-LV","Latvian (Latvia)"],
	[139,"mi","Maori"],
	[140,"mi-NZ","Maori (New Zealand)"],
	[141,"mk","FYRO Macedonian"],
	[142,"mk-MK","FYRO Macedonian (Former Yugoslav Republic of Macedonia)"],
	[143,"mn","Mongolian"],
	[144,"mn-MN","Mongolian (Mongolia)"],
	[145,"mr","Marathi"],
	[146,"mr-IN","Marathi (India)"],
	[147,"ms","Malay"],
	[148,"ms-BN","Malay (Brunei Darussalam)"],
	[149,"ms-MY","Malay (Malaysia)"],
	[150,"mt","Maltese"],
	[151,"mt-MT","Maltese (Malta)"],
	[152,"nb","Norwegian (Bokm?l)"],
	[153,"nb-NO","Norwegian (Bokm?l) (Norway)"],
	[154,"nl","Dutch"],
	[155,"nl-BE","Dutch (Belgium)"],
	[156,"nl-NL","Dutch (Netherlands)"],
	[157,"nn-NO","Norwegian (Nynorsk) (Norway)"],
	[158,"ns","Northern Sotho"],
	[159,"ns-ZA","Northern Sotho (South Africa)"],
	[160,"pa","Punjabi"],
	[161,"pa-IN","Punjabi (India)"],
	[162,"pl","Polish"],
	[163,"pl-PL","Polish (Poland)"],
	[164,"ps","Pashto"],
	[165,"ps-AR","Pashto (Afghanistan)"],
	[166,"pt","Portuguese"],
	[167,"pt-BR","Portuguese (Brazil)"],
	[168,"pt-PT","Portuguese (Portugal)"],
	[169,"qu","Quechua"],
	[170,"qu-BO","Quechua (Bolivia)"],
	[171,"qu-EC","Quechua (Ecuador)"],
	[172,"qu-PE","Quechua (Peru)"],
	[173,"ro","Romanian"],
	[174,"ro-RO","Romanian (Romania)"],
	[175,"ru","Russian"],
	[176,"ru-RU","Russian (Russia)"],
	[177,"sa","Sanskrit"],
	[178,"sa-IN","Sanskrit (India)"],
	[179,"se","Sami (Northern)"],
	[180,"se-FI","Sami (Northern) (Finland)"],
	[181,"se-FI-1","Sami (Skolt) (Finland)"],
	[182,"se-FI-2","Sami (Inari) (Finland)"],
	[183,"se-NO","Sami (Northern) (Norway)"],
	[184,"se-NO-1","Sami (Lule) (Norway)"],
	[185,"se-NO-2","Sami (Southern) (Norway)"],
	[186,"se-SE","Sami (Northern) (Sweden)"],
	[187,"se-SE-1","Sami (Lule) (Sweden)"],
	[188,"se-SE-2","Sami (Southern) (Sweden)"],
	[189,"sk","Slovak"],
	[190,"sk-SK","Slovak (Slovakia)"],
	[191,"sl","Slovenian"],
	[192,"sl-SI","Slovenian (Slovenia)"],
	[193,"sq","Albanian"],
	[194,"sq-AL","Albanian (Albania)"],
	[195,"sr-BA","Serbian (Latin) (Bosnia and Herzegovina)"],
	[196,"sr-BA-1","Serbian (Cyrillic) (Bosnia and Herzegovina)"],
	[197,"sr-SP","Serbian (Latin) (Serbia and Montenegro)"],
	[198,"sr-SP-1","Serbian (Cyrillic) (Serbia and Montenegro)"],
	[199,"sv","Swedish"],
	[200,"sv-FI","Swedish (Finland)"],
	[201,"sv-SE","Swedish (Sweden)"],
	[202,"sw","Swahili"],
	[203,"sw-KE","Swahili (Kenya)"],
	[204,"syr","Syriac"],
	[205,"syr-SY","Syriac (Syria)"],
	[206,"ta","Tamil"],
	[207,"ta-IN","Tamil (India)"],
	[208,"te","Telugu"],
	[209,"te-IN","Telugu (India)"],
	[210,"th","Thai"],
	[211,"th-TH","Thai (Thailand)"],
	[212,"tl","Tagalog"],
	[213,"tl-PH","Tagalog (Philippines)"],
	[214,"tn","Tswana"],
	[215,"tn-ZA","Tswana (South Africa)"],
	[216,"tr","Turkish"],
	[217,"tr-TR","Turkish (Turkey)"],
	[218,"tt","Tatar"],
	[219,"tt-RU","Tatar (Russia)"],
	[220,"ts","Tsonga"],
	[221,"uk","Ukrainian"],
	[222,"uk-UA","Ukrainian (Ukraine)"],
	[223,"ur","Urdu"],
	[224,"ur-PK","Urdu (Islamic Republic of Pakistan)"],
	[225,"uz","Uzbek (Latin)"],
	[226,"uz-UZ","Uzbek (Latin) (Uzbekistan)"],
	[227,"uz-UZ-1","Uzbek (Cyrillic) (Uzbekistan)"],
	[228,"vi","Vietnamese"],
	[229,"vi-VN","Vietnamese (Viet Nam)"],
	[230,"xh","Xhosa"],
	[231,"xh-ZA","Xhosa (South Africa)"],
	[232,"zh","Chinese"],
	[233,"zh-CN","Chinese (S)"],
	[234,"zh-HK","Chinese (Hong Kong)"],
	[235,"zh-MO","Chinese (Macau)"],
	[236,"zh-SG","Chinese (Singapore)"],
	[237,"zh-TW","Chinese (T)"],
	[238,"zu","Zulu"],
	[239,"zu-ZA","Zulu (South Africa)"]
];
